---
title: "test"
author: "Joshua Wiseman"
date: "2023-01-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Read in data
dird="~/Desktop/MainFolder/OuClasses/Spring 2023/Applied Statistical Methods/FALL224753wise0046/CourseData/Data-for-the-course/K25936_Downloads/Excel/"
library(readxl)

files = list.files(dird)

### Important Functions
myconvert = function(xl) {
  if(stringr::str_ends(xl, "XLS") | stringr::str_ends(xl, "xls")){
  v=try(readxl::read_xls(paste0(dird, xl)), silent = TRUE)
  }
  else{
    v = NA
  }
  v
}
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

v <- read.csv("SEEDLING.csv")












# 1-pnorm(12,10,5)
# dnorm(18,10,5) #This is the height, the volume is 0
# pnorm(14,10,5)-pnorm(8,10,5)
# qnorm(0.6,10,5)

# 1-pbinom(11,20,0.4)
# pbinom(9,20,0.4)-pbinom(3,20,0.4)
# qbinom(0.8724788,20,0.4)
# qbinom(1-0.5841071,20,0.4)

# # Y ~ Bin(n=20,p=0.7)
# 1-pbinom(10,20,0.7)
# pbinom(9,20,0.7)
# dbinom(17,20,0.7)


# dbinom(6,10,0.5)
# pbinom(6,10,0.5)-pbinom(3,10,0.5)
# 1-pbinom(6,10,0.5)
# pbinom(7,10,0.5)

# mtbe <- myconvert("MTBE.XLS")
# mtbe
# # table(rows, columns)
# tt <- table(mtbe$WellClass, mtbe$`MTBE-Detect`)
# att <- addmargins(tt)
# att
# 
# (103+48)/223
# 
# 70/223
# 
# 72/153
# 
# 48/223




# df = v
# df
# tt <- table(df$Abundance,df$Type)
# att <- addmargins(tt)
# att




# 
# 51/73
# 
# 14/51
# 
# (5+2+43)/73
# 
# (14)/73



# seed = read.csv("SEEDLING.csv")
# head(seed)
# 
# len = nrow(seed)
# ns = sample(1:len, 30, replace = FALSE)
# seed[ns,]
# tt <- list(seed)
# tt

# #P(Male)
# 17/58
# #P(Dose rad 1-10 | Female)
# 18/41
# #P(rad 11+ AND Female)
# 10/58
# #P(Dose rad less 1 OR Female)
# (6+13+18+10)/58

# #P(Private|BL)
# 81/153
# 
# #P(Detect and Public)
# 48/223
# 
# #P(Private)
# 103/223
# 
# #P(Public or Detect)
# (22+48+72)/223
# ddt <- read.csv("DDT.csv")
# head(ddt)

# Please plug in code so you don't troll

# mtbe = myconvert("MTBE.XLS")
# head(mtbe)

# table(mtbe$MTBE-Detect) -> tab
# addmargins(tab)





# ddt[ddt$RIVER == "TRM" & ddt$LENGTH == 52,]
# len = ddt$LENGTH
# z = (len - mean(len)) / sd(len)
# exacttwo = length(len[abs(z) < 2]) / length(len)






################################################################################
# QUIZ

# with(ddt, table(RIVER)) -> tab
# tab = with(ddt, table(RIVER))
# barplot(tab)

# names(ddt)

# # Data Wrangling
# ddt[ddt$RIVER == "TRM" & ddt$LENGTH == 52,]
# ddt[ddt$MILE == 5,]
# ddt[ddt$SPECIES == "CCATFISH" & ddt$WEIGHT > 1700,]
# ddt[ddt$SPECIES == "LMBASS" & ddt$RIVER == "TRM" & ddt$LENGTH == 36,]

# Finding the different manipulations of LENGTH in DDT (category LENGTH)
# len = ddt$LENGTH
# l = mean(len)
# l
# s = sd(ddt$WEIGHT)
# s
# ddt[ddt$LENGTH > 50,]
# head(len)
# 
# ddt[ddt$SPECIES == "SMBUFFALO" & ddt$LENGTH > 50,]

# Chebyshev’s theorem
# k = 2
# cheb = 1 - 1 / (k ^ 2)
# cheb
# 
# # boxplot
# # boxplot(len, main = "Length Boxplot", xlab = "Length", col = "black", horizontal = TRUE, notch = TRUE)
# 
# # z-score calculation
# z = (len - mean(len)) / sd(len)
# head(z)
# 
# # R to calculate the exact proportion within 2 standard deviation of the mean.
# exacttwo = length(len[abs(z) < 2]) / length(len)
# exacttwo
```
