---
title: "QuizLab1"
author: "Joshua Wiseman"
date: "2023-01-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Read in data
dird="~/Desktop/MainFolder/OuClasses/Spring 2023/Applied Statistical Methods/FALL224753wise0046/CourseData/Data-for-the-course/K25936_Downloads/Excel/"
library(readxl)

files = list.files(dird)

### Important Functions
myconvert = function(xl) {
  if(stringr::str_ends(xl, "XLS") | stringr::str_ends(xl, "xls")){
  v=try(readxl::read_xls(paste0(dird, xl)), silent = TRUE)
  }
  else{
    v = NA
  }
  v
}
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

#P(Private|BL)
81/153

#P(Detect and Public)
48/223

#P(Private)
103/223

#P(Public or Detect)
(22+48+72)/223
# ddt <- read.csv("DDT.csv")
# head(ddt)

# Please plug in code so you don't troll

# mtbe = myconvert("MTBE.XLS")
# head(mtbe)

# table(mtbe$MTBE-Detect) -> tab
# addmargins(tab)





# ddt[ddt$RIVER == "TRM" & ddt$LENGTH == 52,]
# len = ddt$LENGTH
# z = (len - mean(len)) / sd(len)
# exacttwo = length(len[abs(z) < 2]) / length(len)






################################################################################
# QUIZ

# with(ddt, table(RIVER)) -> tab
# tab = with(ddt, table(RIVER))
# barplot(tab)

# names(ddt)

# # Data Wrangling
# ddt[ddt$RIVER == "TRM" & ddt$LENGTH == 52,]
# ddt[ddt$MILE == 5,]
# ddt[ddt$SPECIES == "CCATFISH" & ddt$WEIGHT > 1700,]
# ddt[ddt$SPECIES == "LMBASS" & ddt$RIVER == "TRM" & ddt$LENGTH == 36,]

# Finding the different manipulations of LENGTH in DDT (category LENGTH)
# len = ddt$LENGTH
# l = mean(len)
# l
# s = sd(ddt$WEIGHT)
# s
# ddt[ddt$LENGTH > 50,]
# head(len)
# 
# ddt[ddt$SPECIES == "SMBUFFALO" & ddt$LENGTH > 50,]

# Chebyshev’s theorem
# k = 2
# cheb = 1 - 1 / (k ^ 2)
# cheb
# 
# # boxplot
# # boxplot(len, main = "Length Boxplot", xlab = "Length", col = "black", horizontal = TRUE, notch = TRUE)
# 
# # z-score calculation
# z = (len - mean(len)) / sd(len)
# head(z)
# 
# # R to calculate the exact proportion within 2 standard deviation of the mean.
# exacttwo = length(len[abs(z) < 2]) / length(len)
# exacttwo
```
